let params = new URL(document.location).searchParams;
let query = null;
if (params.has("query")) {
    query = params.get("query");
    document.getElementById("txt").textContent += query;
} else {
    location.href = "../";
}

let data = {
    "Apple": ["Apple", "https://apple.com", "Apple Vision Pro. Welcome to the era of spatial computing. Pre-order from 28.06 at 1:00pm. Also shop for iPhone 15, Mac, iPad, AirPods, HomePod, Apple Watch and more. Services: Apple Trade In, Free delivery and pickup, Financing available, Specialist help."],
    "Google": ["Google", "https://google.com", "Search the world's information, including webpages, images, videos and more. Services: Search, Gmail, Maps, YouTube, Google Drive, Google Photos, Google Workspace."],
    "Amazon": ["Amazon", "https://amazon.com", "Shop online for electronics, apparel, books, DVDs & more. Services: Prime, Free Shipping, Alexa, Whole Foods Market, Amazon Fresh, Amazon Music, Amazon Prime Video."],
    "Facebook": ["Facebook", "https://facebook.com", "Connect with friends and the world around you on Facebook. Services: Social Networking, Messenger, Facebook Watch, Facebook Marketplace."],
    "Microsoft": ["Microsoft", "https://microsoft.com", "Explore the latest in Windows, Office, Surface, and Xbox products and services. Services: Microsoft 365, OneDrive, Microsoft Teams, Azure, LinkedIn, Xbox Live."],
    "Twitter": ["Twitter", "https://twitter.com", "What's happening? Join the conversation and stay informed with real-time updates from people and organizations around the world. Services: Social Networking, Twitter Spaces, Twitter Ads."],
    "Netflix": ["Netflix", "https://netflix.com", "Watch TV shows and movies online. Anytime, anywhere. Services: Streaming, Original Content, Subscription Plans, Multi-Device Support."],
    "YouTube": ["YouTube", "https://youtube.com", "Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube. Services: Video Sharing, YouTube Music, YouTube Premium, YouTube Kids."],
    "Instagram": ["Instagram", "https://instagram.com", "Create and share your photos, stories, and videos with the friends and followers you care about. Services: Social Networking, Instagram Stories, IGTV, Instagram Shopping."],
    "LinkedIn": ["LinkedIn", "https://linkedin.com", "Manage your professional identity. Build and engage with your professional network. Access knowledge, insights and opportunities. Services: Professional Networking, LinkedIn Learning, LinkedIn Premium, Job Search."],
    "Wikipedia": ["Wikipedia", "https://wikipedia.org", "The free encyclopedia that anyone can edit. Services: Information, Free Content, Collaborative Editing, Multilingual."],
    "Reddit": ["Reddit", "https://reddit.com", "The front page of the internet. Discover and discuss the best content from your favorite subreddits. Services: Social News, Discussion Forums, Reddit Gold, Reddit Ads."],
    "Pinterest": ["Pinterest", "https://pinterest.com", "Discover recipes, home ideas, style inspiration and other ideas to try. Services: Social Media, Pinboards, Visual Discovery, Shopping."],
    "Yahoo": ["Yahoo", "https://yahoo.com", "News, email and search are just the beginning. Discover more every day. Services: Email, News, Finance, Sports, Lifestyle, Yahoo Answers."],
    "Bing": ["Bing", "https://bing.com", "Search the web with Bing. Find videos, images, and answers. Services: Search Engine, Bing Ads, Rewards Program, Bing Maps."],
    "eBay": ["eBay", "https://ebay.com", "Buy and sell electronics, cars, fashion apparel, collectibles, sporting goods, digital cameras, baby items, coupons, and everything else on eBay. Services: Online Marketplace, Auctions, eBay Stores, eBay Motors."],
    "ESPN": ["ESPN", "https://espn.com", "Visit ESPN for live scores, highlights and sports news. Streaming Services: ESPN+, ESPN App, Fantasy Sports, Live Sports Coverage."],
    "CNN": ["CNN", "https://cnn.com", "Breaking News, Latest News and Videos. Services: News, Live TV, CNN International, CNN Español, Newsletters."],
    "BBC": ["BBC", "https://bbc.com", "The home of BBC News, Sport, TV, Radio, iPlayer and CBBC. Services: News, Radio, Television, iPlayer, BBC World Service."],
    "New York Times": ["New York Times", "https://nytimes.com", "Breaking news and analysis on politics, business, world national news, entertainment, and more. Services: News, Subscriptions, New York Times App, NYT Cooking."],
    "The Guardian": ["The Guardian", "https://theguardian.com", "Latest news, sport, business, comment, analysis and reviews from the Guardian. Services: News, Opinion, Sport, Culture, Lifestyle, Podcasts."],
    "Washington Post": ["Washington Post", "https://washingtonpost.com", "Breaking news and analysis on politics, world news, business, sports, entertainment and more. Services: News, Subscriptions, Washington Post App, Opinions."],
    "Forbes": ["Forbes", "https://forbes.com", "Business News and Financial News. Services: Business, Investing, Technology, Entrepreneurship, Leadership, Lifestyle."],
    "Bloomberg": ["Bloomberg", "https://bloomberg.com", "Business and Financial News. Services: Markets, Technology, Politics, Bloomberg TV, Bloomberg Radio, Bloomberg Terminal."],
    "Reuters": ["Reuters", "https://reuters.com", "Business and Financial News, Breaking News, World News and Video. Services: News, Pictures, Video, Analysis, Reuters Plus."],
    "BuzzFeed": ["BuzzFeed", "https://buzzfeed.com", "News, videos, quizzes, and the latest buzz. Services: News, Entertainment, Quizzes, Tasty, Goodful, BuzzFeed Shopping."],
    "HuffPost": ["HuffPost", "https://huffpost.com", "Breaking news, US and world news, politics, tech and business news. Services: News, Politics, Lifestyle, Entertainment, HuffPost Live."],
    "Quora": ["Quora", "https://quora.com", "A place to share knowledge and better understand the world. Services: Questions and Answers, Blogs, Spaces, Quora Ads."],
    "Medium": ["Medium", "https://medium.com", "Read and share stories that matter. Services: Blogging, Subscription, Medium Partner Program, Publications."],
    "GitHub": ["GitHub", "https://github.com", "The world's leading software development platform. Services: Version Control, GitHub Actions, GitHub Packages, GitHub Pages, GitHub Sponsors."],
    "Stack Overflow": ["Stack Overflow", "https://stackoverflow.com", "Where Developers Learn, Share, & Build Careers. Services: Questions and Answers, Stack Exchange, Jobs, Talent."],
    "Coursera": ["Coursera", "https://coursera.org", "Build skills with courses, certificates, and degrees online from world-class universities and companies. Services: Online Courses, Degrees, Certificates, Specializations."],
    "Udemy": ["Udemy", "https://udemy.com", "Expand your career opportunities with a wide range of skills. Services: Online Courses, Certificates, Udemy for Business, Udemy Mobile App."],
    "Khan Academy": ["Khan Academy", "https://khanacademy.org", "Free Online Courses, Lessons & Practice. Services: Educational Content, Practice Exercises, Teacher Tools, Khan Academy Kids."],
    "TED": ["TED", "https://ted.com", "TED Talks are influential videos from expert speakers on education, business, science, tech and creativity. Services: TED Talks, TED-Ed, TEDx, TED Fellows."],
    "Twitch": ["Twitch", "https://twitch.tv", "Live streaming, watch and chat now with millions of fans worldwide. Services: Live Streaming, Twitch Prime, Twitch Bits, Subscriptions."],
    "Spotify": ["Spotify", "https://spotify.com", "Listen to music and podcasts on the go. Services: Music Streaming, Podcasts, Spotify Premium, Spotify Free, Spotify for Artists."],
    "SoundCloud": ["SoundCloud", "https://soundcloud.com", "Discover, stream, and share a constantly expanding mix of music from emerging and major artists around the world. Services: Music Streaming, SoundCloud Go, SoundCloud Premier, SoundCloud Pulse."],
    "Dropbox": ["Dropbox", "https://dropbox.com", "Bring your files together in one central place. Services: Cloud Storage, Dropbox Paper, Dropbox Business, Dropbox Transfer."],
    "Slack": ["Slack", "https://slack.com", "Where work happens. Services: Team Communication, Channels, Slack Connect, Slack Apps, Integrations."],
    "Zoom": ["Zoom", "https://zoom.us", "Video Conferencing, Web Conferencing, Webinars, Screen Sharing. Services: Zoom Meetings, Zoom Webinars, Zoom Rooms, Zoom Phone."],
    "Salesforce": ["Salesforce", "https://salesforce.com", "The Customer Success Platform. Services: CRM, Customer Service, Marketing Automation, Salesforce Cloud, Salesforce Platform."],
    "Shopify": ["Shopify", "https://shopify.com", "Build your business with Shopify to sell online, offline, and everywhere in between. Services: Ecommerce Platform, Shopify POS, Shopify Plus, Shopify App Store."],
    "Adobe": ["Adobe", "https://adobe.com", "Creative Cloud, Marketing Cloud, Document Cloud. Services: Photoshop, Illustrator, Adobe Acrobat, Adobe XD, Adobe Stock."],
    "Oracle": ["Oracle", "https://oracle.com", "Integrated cloud applications and platform services. Services: Oracle Cloud, Oracle Database, ERP, HCM, SCM."],
    "IBM": ["IBM", "https://ibm.com", "IBM Cloud, AI, and Data Solutions. Services: Watson, IBM Cloud, IBM Services, IBM Systems, IBM Security."],
    "Intel": ["Intel", "https://intel.com", "Data-centric solutions to drive innovation. Services: Processors, Intel Core, Intel Xeon, Intel NUC, Intel Optane."],
    "AMD": ["AMD", "https://amd.com", "High-performance computing products. Services: Ryzen, Radeon, EPYC, Instinct, AMD Software."],
    "NVIDIA": ["NVIDIA", "https://nvidia.com", "Pioneering computing technology. Services: GeForce, Quadro, Tesla, NVIDIA RTX, NVIDIA AI."],
    "Samsung": ["Samsung", "https://samsung.com", "Discover the latest in electronic & smart appliance technology. Services: Mobile Phones, TVs, Home Appliances, Wearables, SmartThings."],
    "Sony": ["Sony", "https://sony.com", "Discover a wide range of high quality products. Services: PlayStation, Sony Electronics, Sony Music, Sony Pictures, Alpha Cameras."],
    "LG": ["LG", "https://lg.com", "Experience innovative technology. Services: Home Appliances, Home Entertainment, Mobile Communications, Air Solutions, Vehicle Component Solutions."],
    "Huawei": ["Huawei", "https://huawei.com", "Leading global provider of ICT infrastructure and smart devices. Services: Smartphones, Tablets, Wearables, Laptops, Network Solutions."],
    "Xiaomi": ["Xiaomi", "https://mi.com", "Innovative technology for everyone. Services: Smartphones, Mi TV, Mi Laptops, Mi Ecosystem, Mi Home."],
    "TikTok": ["TikTok", "https://tiktok.com", "Make Your Day. Services: Short-form Video, TikTok Trends, TikTok for Business, TikTok LIVE."],
    "Snapchat": ["Snapchat", "https://snapchat.com", "Share the moment. Services: Snaps, Stories, Discover, Snap Map, Bitmoji."],
    "WhatsApp": ["WhatsApp", "https://whatsapp.com", "Simple. Secure. Reliable messaging. Services: Messaging, Voice Calls, Video Calls, WhatsApp Web, WhatsApp Business."],
    "Telegram": ["Telegram", "https://telegram.org", "Fast. Secure. Powerful. Services: Messaging, Voice Calls, Video Calls, Telegram Bots, Telegram Channels."],
    "Signal": ["Signal", "https://signal.org", "Say Hello to Privacy. Services: Messaging, Voice Calls, Video Calls, Signal Protocol, Secure Communication."],
    "Viber": ["Viber", "https://viber.com", "Free and secure calls and messages to anyone, anywhere. Services: Messaging, Voice Calls, Video Calls, Viber Out, Viber Communities."],
    "WeChat": ["WeChat", "https://wechat.com", "A better way to connect. Services: Messaging, Voice Calls, Video Calls, WeChat Pay, WeChat Moments."],
    "LINE": ["LINE", "https://line.me", "Free messaging, voice calls, and video calls. Services: Messaging, Voice Calls, Video Calls, LINE Pay, LINE Games."],
    "Discord": ["Discord", "https://discord.com", "Chat, hang out, and stay close with your friends and communities. Services: Voice Chat, Text Chat, Video Chat, Discord Servers, Nitro."],
    "WordPress": ["WordPress", "https://wordpress.com", "Create your new website for free. Services: Website Creation, Blogging, Plugins, Themes, WordPress.com."],
    "Wix": ["Wix", "https://wix.com", "Create a website you're proud of. Services: Website Builder, Wix ADI, Wix App Market, Wix Stores, Wix SEO."],
    "Squarespace": ["Squarespace", "https://squarespace.com", "Build a beautiful website. Services: Website Builder, Online Store, Domains, Marketing Tools, Analytics."],
    "GoDaddy": ["GoDaddy", "https://godaddy.com", "Make your idea real. Services: Domains, Website Builder, Hosting, Professional Email, Online Store."],
    "Bluehost": ["Bluehost", "https://bluehost.com", "Web Hosting, Domain Names, WordPress Hosting. Services: Shared Hosting, VPS Hosting, Dedicated Hosting, Professional Services, Marketing Services."],
    "HostGator": ["HostGator", "https://hostgator.com", "Web Hosting for Your Website. Services: Shared Hosting, VPS Hosting, Dedicated Hosting, Website Builder, Marketing Services."],
    "SiteGround": ["SiteGround", "https://siteground.com", "Crafted for Easy Website Management. Services: Web Hosting, WordPress Hosting, WooCommerce Hosting, Cloud Hosting, Domain Services."],
    "DigitalOcean": ["DigitalOcean", "https://digitalocean.com", "Simplify cloud computing. Services: Droplets, Kubernetes, Managed Databases, Spaces, App Platform."],
    "Heroku": ["Heroku", "https://heroku.com", "The cloud platform for developers. Services: PaaS, Heroku Enterprise, Heroku Add-ons, Heroku Postgres, Heroku Connect."],
    "Dropbox Paper": ["Dropbox Paper", "https://dropbox.com/paper", "Collaborative document-editing service. Services: Document Collaboration, Task Management, Integrations, Templates, Mobile App."],
    "Notion": ["Notion", "https://notion.so", "All-in-one workspace. Services: Notes, Tasks, Wikis, Databases, Integrations."],
    "Trello": ["Trello", "https://trello.com", "Collaborate, manage projects, and reach new productivity peaks. Services: Boards, Lists, Cards, Power-Ups, Butler Automation."],
    "Asana": ["Asana", "https://asana.com", "Manage your team’s work, projects, & tasks online. Services: Work Management, Task Management, Project Management, Timeline, Workload."],
    "Basecamp": ["Basecamp", "https://basecamp.com", "Organize your business. Services: Project Management, Team Collaboration, To-Dos, Scheduling, File Sharing."],
    "Monday.com": ["Monday.com", "https://monday.com", "Work Without Limits. Services: Work OS, Task Management, Project Management, CRM, Marketing."],
    "Airtable": ["Airtable", "https://airtable.com", "Part spreadsheet, part database. Services: Relational Database, Project Management, Collaboration, Integrations, Automations."],
    "Jira": ["Jira", "https://jira.com", "The #1 software development tool used by agile teams. Services: Issue Tracking, Project Management, Agile Boards, Roadmaps, Reports."],
    "Confluence": ["Confluence", "https://confluence.com", "Create, collaborate, and organize your work in one place. Services: Team Collaboration, Document Management, Knowledge Base, Integrations, Templates."],
    "Bitbucket": ["Bitbucket", "https://bitbucket.org", "Git code management. Services: Source Code Management, Pull Requests, Pipelines, Integrations, Bitbucket Server."],
    "Toggl": ["Toggl", "https://toggl.com", "Time tracking software. Services: Time Tracking, Project Management, Reporting, Integrations, Toggl Track."],
    "Harvest": ["Harvest", "https://getharvest.com", "Time Tracking and Invoicing Software. Services: Time Tracking, Invoicing, Project Management, Reporting, Integrations."],
    "RescueTime": ["RescueTime", "https://rescuetime.com", "Take control of your time. Services: Time Management, Productivity Tracking, Focus Sessions, Goals, Reporting."],
    "Clockify": ["Clockify", "https://clockify.me", "Free time tracker for teams. Services: Time Tracking, Timesheets, Reports, Integrations, Mobile App."],
    "HubSpot": ["HubSpot", "https://hubspot.com", "Inbound Marketing, Sales, and Service Software. Services: CRM, Marketing Hub, Sales Hub, Service Hub, CMS Hub."],
    "Mailchimp": ["Mailchimp", "https://mailchimp.com", "Marketing, Automation & Email Platform. Services: Email Marketing, Marketing Automation, Customer Journeys, Templates, Analytics."],
    "Constant Contact": ["Constant Contact", "https://constantcontact.com", "Email Marketing Services. Services: Email Marketing, Marketing Automation, Social Campaigns, Event Marketing, Email Templates."],
    "AWeber": ["AWeber", "https://aweber.com", "Email Marketing and More. Services: Email Marketing, Landing Pages, Email Automation, Templates, Reporting."],
    "GetResponse": ["GetResponse", "https://getresponse.com", "Email Marketing Platform. Services: Email Marketing, Marketing Automation, Webinars, Landing Pages, Conversion Funnels."],
    "ActiveCampaign": ["ActiveCampaign", "https://activecampaign.com", "Customer Experience Automation. Services: Email Marketing, Automation, Sales Automation, CRM, Messaging."],
    "Sendinblue": ["Sendinblue", "https://sendinblue.com", "All Your Digital Marketing Tools in One Place. Services: Email Marketing, SMS Marketing, Marketing Automation, Chat, CRM."],
    "Klaviyo": ["Klaviyo", "https://klaviyo.com", "Email & SMS Marketing Platform. Services: Email Marketing, SMS Marketing, Automation, Personalization, Integrations."],
    "Campaign Monitor": ["Campaign Monitor", "https://campaignmonitor.com", "Email Marketing and Automation Platform. Services: Email Marketing, Marketing Automation, Email Templates, Analytics, Transactional Emails."],
    "Salesforce Marketing Cloud": ["Salesforce Marketing Cloud", "https://salesforce.com/products/marketing-cloud/overview", "Connect to your customers in a whole new way. Services: Email Marketing, Social Media Marketing, Mobile Marketing, Customer Journey Management, Advertising."],
    "Pardot": ["Pardot", "https://pardot.com", "B2B Marketing Automation by Salesforce. Services: Lead Generation, Lead Nurturing, Lead Management, Email Marketing, Analytics."],
    "Marketo": ["Marketo", "https://marketo.com", "Marketing Automation Software. Services: Lead Management, Email Marketing, Consumer Marketing, Customer Base Marketing, Mobile Marketing."],
    "Hootsuite": ["Hootsuite", "https://hootsuite.com", "Manage all your social media in one place. Services: Social Media Management, Scheduling, Analytics, Monitoring, Team Collaboration."],
    "Buffer": ["Buffer", "https://buffer.com", "Grow your audience on social media. Services: Social Media Management, Scheduling, Analytics, Engagement, Team Collaboration."],
    "Sprout Social": ["Sprout Social", "https://sproutsocial.com", "Real people. Real brands. Real connection. Services: Social Media Management, Social Media Listening, Social Media Analytics, Social Media Publishing, Employee Advocacy."],
    "Bitly": ["Bitly", "https://bitly.com", "Shorten, create and share trusted, powerful links for your business. Services: URL Shortening, Link Management, Branded Links, Analytics, QR Codes."],
    "TinyURL": ["TinyURL", "https://tinyurl.com", "Shorten That Long URL into a Tiny URL. Services: URL Shortening, Custom Aliases, Analytics, QR Codes, Browser Extensions."],
    "Ow.ly": ["Ow.ly", "https://ow.ly", "Shorten links, measure traffic, and demonstrate social ROI. Services: URL Shortening, Link Management, Analytics, QR Codes, Social Media Integration."],
    "Rebrandly": ["Rebrandly", "https://rebrandly.com", "Branded link management platform. Services: URL Shortening, Custom Domains, Link Management, Analytics, API."],
    "Bitdefender": ["Bitdefender", "https://bitdefender.com", "Cybersecurity Solutions. Services: Antivirus, Internet Security, Total Security, VPN, Endpoint Security."],
    "Norton": ["Norton", "https://norton.com", "Protect your digital life with Norton 360. Services: Antivirus, VPN, Identity Theft Protection, Secure Cloud Backup, Password Manager."],
    "McAfee": ["McAfee", "https://mcafee.com", "Comprehensive internet security solutions. Services: Antivirus, Identity Protection, VPN, Safe Family, Total Protection."],
    "Kaspersky": ["Kaspersky", "https://kaspersky.com", "Security solutions for home and business. Services: Antivirus, Internet Security, Total Security, VPN, Endpoint Security."],
    "Avast": ["Avast", "https://avast.com", "Free Antivirus and VPN. Services: Antivirus, Internet Security, SecureLine VPN, Passwords, Cleanup."],
    "ESET": ["ESET", "https://eset.com", "Antivirus and Internet Security Solutions. Services: NOD32 Antivirus, Internet Security, Smart Security, Endpoint Protection, Cyber Security Training."],
    "LastPass": ["LastPass", "https://lastpass.com", "Password Manager, Auto-pilot for all your passwords. Services: Password Management, Secure Notes, Password Generator, Dark Web Monitoring, MFA."],
    "1Password": ["1Password", "https://1password.com", "The best way to keep you and your family, team, and business safe online. Services: Password Management, Secure Notes, Password Generator, Watchtower, MFA."],
    "Dashlane": ["Dashlane", "https://dashlane.com", "Password Manager for Business and Personal Use. Services: Password Management, Secure Notes, Password Generator, Dark Web Monitoring, VPN."],
    "NordPass": ["NordPass", "https://nordpass.com", "Keep your passwords safe and secure. Services: Password Management, Secure Notes, Password Generator, Data Breach Scanner, MFA."],
    "Google Keep": ["Google Keep", "https://keep.google.com", "Capture what's on your mind. Services: Notes, Checklists, Voice Memos, Reminders, Collaborations."],
    "Evernote": ["Evernote", "https://evernote.com", "Remember everything and tackle any project with your notes, tasks, and schedule all in one place. Services: Note-Taking, Task Management, Web Clipper, Document Scanning, Integrations."],
    "OneNote": ["OneNote", "https://onenote.com", "Your digital notebook. Services: Note-Taking, Organization, Collaboration, Web Clipper, Integrations."],
    "Notability": ["Notability", "https://notability.com", "Powerful, yet wonderfully simple note-taking and PDF annotation. Services: Note-Taking, PDF Annotation, Handwriting, Audio Recording, Multi-Device Sync."],
    "GoodNotes": ["GoodNotes", "https://goodnotes.com", "Best note-taking app for iPad and Mac. Services: Note-Taking, PDF Annotation, Handwriting, Document Management, Multi-Device Sync."],
    "Simplenote": ["Simplenote", "https://simplenote.com", "The simplest way to keep notes. Services: Note-Taking, Markdown Support, Tagging, Version History, Multi-Device Sync."],
    "Bear": ["Bear", "https://bear.app", "Write beautifully on iPhone, iPad, and Mac. Services: Note-Taking, Markdown Support, Tagging, Export Options, Multi-Device Sync."],
    "Todoist": ["Todoist", "https://todoist.com", "The best to-do list app for you and your team. Services: Task Management, Project Management, Collaboration, Integrations, Productivity Reports."],
    "Microsoft To Do": ["Microsoft To Do", "https://todo.microsoft.com", "Stay organized and manage your day-to-day. Services: Task Management, Daily Planner, Lists, Reminders, Microsoft 365 Integration."],
    "Any.do": ["Any.do", "https://any.do", "To-do list, Calendar, Planner & Reminders. Services: Task Management, Calendar, Reminders, Collaboration, Integrations."],
    "TickTick": ["TickTick", "https://ticktick.com", "Your productivity partner. Services: Task Management, Calendar, Reminders, Pomodoro Timer, Habit Tracker."],
    "Wunderlist": ["Wunderlist", "https://wunderlist.com", "Create and share to-do lists. Services: Task Management, Collaboration, Reminders, Subtasks, Multi-Device Sync."],
    "Remember The Milk": ["Remember The Milk", "https://rememberthemilk.com", "The smart to-do app for busy people. Services: Task Management, Reminders, Subtasks, Tags, Integrations."],
    "Habitica": ["Habitica", "https://habitica.com", "Gamify Your Life. Services: Habit Tracker, Task Management, RPG Elements, Rewards, Social Features."],
    "Google Calendar": ["Google Calendar", "https://calendar.google.com", "A calendar that's easy to use. Services: Calendar, Scheduling, Reminders, Goals, Integrations."],
    "Outlook Calendar": ["Outlook Calendar", "https://outlook.live.com/calendar", "Stay on top of your schedule. Services: Calendar, Scheduling, Reminders, Microsoft 365 Integration, Shared Calendars."],
    "Fantastical": ["Fantastical", "https://fantastical.app", "The calendar app you won't be able to live without. Services: Calendar, Scheduling, Reminders, Weather Forecasts, Integrations."],
    "Timepage": ["Timepage", "https://moleskine.com/en/timepage", "The essential planner for iPhone, iPad, Mac, and Apple Watch. Services: Calendar, Scheduling, Weather Forecasts, Reminders, Integrations."],
    "Calendly": ["Calendly", "https://calendly.com", "Easy scheduling ahead. Services: Scheduling, Appointment Booking, Meeting Coordination, Integrations, Customization."],
    "Doodle": ["Doodle", "https://doodle.com", "The simplest way to schedule meetings with clients, colleagues, or friends. Services: Scheduling, Polls, Meeting Coordination, Calendar Integration, Reminders."],
    "ZoomInfo": ["ZoomInfo", "https://zoominfo.com", "B2B Database and Business Data. Services: Sales Intelligence, B2B Contact Data, Lead Generation, Account-Based Marketing, Data Management."],
    "Clearbit": ["Clearbit", "https://clearbit.com", "Data to power your business. Services: B2B Data Enrichment, Lead Generation, Sales Intelligence, API, Integrations."],
    "Apollo.io": ["Apollo.io", "https://apollo.io", "Sales Intelligence and Engagement Platform. Services: B2B Data, Lead Generation, Email Sequences, CRM Integration, Analytics."],
    "Lusha": ["Lusha", "https://lusha.com", "B2B Contact and Company Information. Services: Sales Intelligence, Lead Enrichment, CRM Integration, Prospecting, API."],
    "Hunter.io": ["Hunter.io", "https://hunter.io", "Find email addresses in seconds. Services: Email Finder, Email Verifier, Email Campaigns, Domain Search, API."],
    "BuiltWith": ["BuiltWith", "https://builtwith.com", "Web technology information profiler tool. Services: Technology Lookups, Lead Generation, Competitive Analysis, Website Analytics, API."],
    "SimilarWeb": ["SimilarWeb", "https://similarweb.com", "The official measure of the digital world. Services: Website Traffic Analysis, Competitive Analysis, Market Research, Digital Marketing Intelligence, Investor Intelligence."],
    "Alexa": ["Alexa", "https://alexa.com", "Actionable Analytics for the Web. Services: Website Traffic Statistics, SEO Tools, Competitive Analysis, Audience Insights, Keyword Research."],
    "Ahrefs": ["Ahrefs", "https://ahrefs.com", "Tools to grow your search traffic, research your competitors, and monitor your niche. Services: SEO Tools, Site Explorer, Keywords Explorer, Content Explorer, Rank Tracker."],
    "SEMrush": ["SEMrush", "https://semrush.com", "Online visibility management and content marketing SaaS platform. Services: SEO Tools, Keyword Research, Competitive Analysis, Site Audit, Content Marketing."],
    "Moz": ["Moz", "https://moz.com", "SEO Software, Tools, and Resources for Smarter Marketing. Services: Keyword Research, SEO Audit, Rank Tracking, Backlink Analysis, Content Optimization."],
    "SpyFu": ["SpyFu", "https://spyfu.com", "Competitor Keyword Research Tools for PPC & SEO. Services: Competitor Analysis, Keyword Research, SEO Tools, PPC Research, Rank Tracking."],
    "Serpstat": ["Serpstat", "https://serpstat.com", "All-in-one SEO platform for agencies and in-house teams. Services: Keyword Research, Competitor Analysis, Site Audit, Rank Tracking, Backlink Analysis."],
    "Ubersuggest": ["Ubersuggest", "https://neilpatel.com/ubersuggest", "Free Keyword Tool, Competitive Analysis, Website Analyzer. Services: Keyword Research, SEO Audit, Rank Tracking, Content Ideas, Backlink Data."],
    "Yoast SEO": ["Yoast SEO", "https://yoast.com", "SEO for everyone. Services: SEO Plugins, SEO Courses, SEO Consulting, Content Analysis, Technical SEO."],
    "Rank Math": ["Rank Math", "https://rankmath.com", "The Swiss Army Knife of WordPress SEO. Services: SEO Plugin, Content Optimization, Keyword Tracking, Schema Markup, Local SEO."],
    "Elementor": ["Elementor", "https://elementor.com", "Create WordPress Websites, Visually. Services: WordPress Website Builder, Theme Builder, WooCommerce Builder, Landing Page Builder, Marketing Tools."],
    "Divi": ["Divi", "https://elegantthemes.com/divi", "The most popular WordPress Theme in the world. Services: WordPress Theme, Visual Page Builder, Theme Builder, WooCommerce Builder, Design Tools."],
    "Beaver Builder": ["Beaver Builder", "https://wpbeaverbuilder.com", "WordPress Page Builder Plugin. Services: Page Builder, Theme Builder, WooCommerce Builder, Design Tools, Templates."],
    "Visual Composer": ["Visual Composer", "https://visualcomposer.com", "The best website builder for WordPress. Services: Website Builder, Theme Builder, Design Tools, Templates, Integrations."],
    "Brizy": ["Brizy", "https://brizy.io", "Create websites fast & easy. Services: WordPress Page Builder, Theme Builder, WooCommerce Builder, Popups, Design Tools."],
    "Oxygen Builder": ["Oxygen Builder", "https://oxygenbuilder.com", "Build websites with less effort. Services: WordPress Site Builder, Visual Builder, WooCommerce Builder, Design Tools, Integrations."],
    "WPBakery": ["WPBakery", "https://wpbakery.com", "Page Builder for WordPress. Services: Page Builder, Design Tools, Templates, WooCommerce Builder, Integrations."],
    "Avada": ["Avada", "https://theme-fusion.com/avada", "#1 Selling WordPress Theme of All Time. Services: WordPress Theme, Website Builder, WooCommerce Builder, Design Tools, Templates."],
    "Flatsome": ["Flatsome", "https://flatsome3.uxthemes.com", "The Best Selling WooCommerce Theme. Services: WooCommerce Theme, Page Builder, Design Tools, Templates, UX Builder."],
    "Astra": ["Astra", "https://wpastra.com", "The Most Popular Theme of All Time. Services: WordPress Theme, Page Builder, WooCommerce Builder, Performance Tools, Design Tools."],
    "OceanWP": ["OceanWP", "https://oceanwp.org", "Create your own unique and beautiful website. Services: WordPress Theme, Page Builder, WooCommerce Builder, Extensions, Design Tools."],
    "GeneratePress": ["GeneratePress", "https://generatepress.com", "The perfect lightweight theme for your next project. Services: WordPress Theme, Page Builder, WooCommerce Builder, Design Tools, Performance Tools."],
    "Neve": ["Neve", "https://themeisle.com/themes/neve", "Super Fast, Featherweight & Easily Customizable WP Theme. Services: WordPress Theme, Page Builder, WooCommerce Builder, Design Tools, Templates."],
    "Hestia": ["Hestia", "https://themeisle.com/themes/hestia", "The All-in-One WordPress Theme for your Business. Services: WordPress Theme, Page Builder, WooCommerce Builder, Design Tools, Templates."],
    "Schema Pro": ["Schema Pro", "https://wpschema.com", "Automated Schema Markup Plugin for WordPress. Services: Schema Markup, SEO Tools, Rich Snippets, JSON-LD Markup, Local SEO."],
    "Cloudflare": ["Cloudflare", "https://cloudflare.com", "The foundation for your infrastructure, applications, and teams. Services: CDN, DDoS Protection, Web Application Firewall, DNS, Zero Trust Security."],
    "Akamai": ["Akamai", "https://akamai.com", "Intelligent Edge Platform. Services: CDN, DDoS Protection, Web Application Firewall, Bot Management, Cloud Security."],
    "Amazon CloudFront": ["Amazon CloudFront", "https://aws.amazon.com/cloudfront", "Fast, secure, and programmable content delivery. Services: CDN, DDoS Protection, Web Application Firewall, SSL/TLS, Edge Computing."],
    "Fastly": ["Fastly", "https://fastly.com", "Powering fast, secure, and scalable online experiences. Services: CDN, DDoS Protection, Web Application Firewall, Edge Computing, Real-Time Analytics."],
    "StackPath": ["StackPath", "https://stackpath.com", "A cloud platform built to secure and accelerate the internet. Services: CDN, DDoS Protection, Web Application Firewall, Edge Computing, SSL/TLS."],
    "KeyCDN": ["KeyCDN", "https://keycdn.com", "Powerful and easy to use content delivery network. Services: CDN, DDoS Protection, HTTP/2, Real-Time Analytics, Secure Token."],
    "Netlify": ["Netlify", "https://netlify.com", "Build, deploy, and scale modern web projects. Services: Web Hosting, Serverless Functions, CDN, Continuous Deployment, Analytics."],
    "Vercel": ["Vercel", "https://vercel.com", "Develop. Preview. Ship. Services: Frontend Hosting, Serverless Functions, Edge Network, Analytics, Integrations."],
    "Render": ["Render", "https://render.com", "Cloud to scale your applications and websites. Services: Web Hosting, Serverless Functions, Databases, CDN, Analytics."],
    "Heroku": ["Heroku", "https://heroku.com", "The cloud platform for developers. Services: PaaS, Heroku Enterprise, Heroku Add-ons, Heroku Postgres, Heroku Connect."],
    "DigitalOcean": ["DigitalOcean", "https://digitalocean.com", "Simplify cloud computing. Services: Droplets, Kubernetes, Managed Databases, Spaces, App Platform."],
    "Linode": ["Linode", "https://linode.com", "The independent open cloud for developers. Services: Cloud Computing, Kubernetes, Networking, Managed Databases, Object Storage."],
    "Vultr": ["Vultr", "https://vultr.com", "Infrastructure Cloud. Services: Cloud Compute, Kubernetes, Bare Metal, Block Storage, DDoS Protection."],
    "OVHcloud": ["OVHcloud", "https://ovhcloud.com", "Trusted and Secure Cloud Solutions. Services: Public Cloud, Private Cloud, Bare Metal, Web Hosting, Managed Databases."],
    "Google Cloud Platform": ["Google Cloud Platform", "https://cloud.google.com", "Building blocks for modern cloud-native applications. Services: Compute Engine, App Engine, Kubernetes Engine, Cloud Storage, BigQuery."],
    "Microsoft Azure": ["Microsoft Azure", "https://azure.microsoft.com", "Innovate anywhere with Azure. Services: Virtual Machines, App Services, Azure Kubernetes Service, Azure Functions, SQL Database."],
    "Amazon Web Services": ["Amazon Web Services", "https://aws.amazon.com", "The most comprehensive and broadly adopted cloud platform. Services: EC2, S3, RDS, Lambda, Redshift."],
    "IBM Cloud": ["IBM Cloud", "https://cloud.ibm.com", "Build and scale with confidence. Services: Cloud Compute, Cloud Databases, AI & Machine Learning, Containers, DevOps."],
    "Oracle Cloud": ["Oracle Cloud", "https://oracle.com/cloud", "Build, run, and grow your business with Oracle Cloud. Services: Compute, Autonomous Database, Cloud Applications, OCI, Security."],
    "SAP Cloud Platform": ["SAP Cloud Platform", "https://sap.com/products/technology-platform.html", "Enterprise platform-as-a-service. Services: Cloud Applications, Data Management, Analytics, IoT, AI."],
    "DigitalOcean App Platform": ["DigitalOcean App Platform", "https://www.digitalocean.com/products/app-platform", "Build, deploy, and scale apps quickly. Services: App Deployment, GitHub Integration, SSL/TLS, Scalability, Monitoring."],
    "Netlify Functions": ["Netlify Functions", "https://www.netlify.com/products/functions/", "Serverless functions made simple. Services: Serverless Functions, AWS Lambda, Git Integration, APIs, Deploy Previews."],
    "Vercel Functions": ["Vercel Functions", "https://vercel.com/features/functions", "API endpoints for modern web projects. Services: Serverless Functions, Edge Functions, HTTP APIs, Integrations, Monitoring."],
    "AWS Lambda": ["AWS Lambda", "https://aws.amazon.com/lambda", "Run code without thinking about servers. Services: Serverless Computing, Event-Driven, Auto Scaling, Cost-Effective, Flexible."],
    "Google Cloud Functions": ["Google Cloud Functions", "https://cloud.google.com/functions", "Event-driven serverless compute. Services: Serverless Functions, Event-Driven, Auto Scaling, Cost-Effective, Integrated Monitoring."],
    "Azure Functions": ["Azure Functions", "https://azure.microsoft.com/services/functions", "Compute-on-demand in a serverless environment. Services: Serverless Computing, Event-Driven, Auto Scaling, Cost-Effective, Integrated Monitoring."],
    "IBM Cloud Functions": ["IBM Cloud Functions", "https://cloud.ibm.com/functions", "Event-driven programming for the cloud. Services: Serverless Functions, Event-Driven, Auto Scaling, Cost-Effective, OpenWhisk."],
    "Oracle Functions": ["Oracle Functions", "https://www.oracle.com/cloud/functions/", "Serverless functions powered by Fn Project. Services: Serverless Computing, Event-Driven, Auto Scaling, Cost-Effective, Oracle Cloud Integration."],
    "Serverless Framework": ["Serverless Framework", "https://serverless.com", "Build auto-scaling applications on AWS Lambda, Azure Functions, and more. Services: Serverless Development, API Gateway, Monitoring, Event-Driven, Multi-Cloud."],
    "Google Analytics": ["Google Analytics", "https://analytics.google.com", "Understand your customers to better evaluate the performance of your marketing, content, products, and more. Services: Website Analytics, App Analytics, Audience Insights, Reporting, Data Visualization."],
    "Adobe Analytics": ["Adobe Analytics", "https://adobe.com/analytics", "Turn customer data into action. Services: Web Analytics, Multichannel Analysis, Predictive Analytics, Segmentation, Reporting."],
    "Matomo": ["Matomo", "https://matomo.org", "Ethical Analytics. Powerful Insights. Services: Web Analytics, Heatmaps, Session Recording, Tag Manager, SEO Tools."],
    "Mixpanel": ["Mixpanel", "https://mixpanel.com", "Powerful, self-serve product analytics. Services: Product Analytics, Event Tracking, User Segmentation, A/B Testing, Reporting."],
    "Amplitude": ["Amplitude", "https://amplitude.com", "Optimize your digital product experiences. Services: Product Analytics, Event Tracking, User Segmentation, A/B Testing, Reporting."],
    "Heap": ["Heap", "https://heap.io", "Data to every decision. Services: Product Analytics, Event Tracking, User Segmentation, A/B Testing, Reporting."],
    "Hotjar": ["Hotjar", "https://hotjar.com", "See how visitors are really using your website. Services: Heatmaps, Session Recordings, Surveys, Feedback, Analytics."],
    "Crazy Egg": ["Crazy Egg", "https://crazyegg.com", "Website optimization made easy. Services: Heatmaps, Scrollmaps, Session Recordings, A/B Testing, User Feedback."],
    "FullStory": ["FullStory", "https://fullstory.com", "A better way to build, measure, and optimize digital experiences. Services: Session Replay, Heatmaps, User Journeys, Conversions, Integrations."],
    "Pendo": ["Pendo", "https://pendo.io", "Deliver the digital experiences your users want. Services: Product Analytics, User Feedback, Onboarding, In-App Messaging, Roadmaps."],
    "WalkMe": ["WalkMe", "https://walkme.com", "Take digital adoption to the next level. Services: Digital Adoption Platform, User Onboarding, In-App Guidance, Insights, Automation."],
    "Appcues": ["Appcues", "https://appcues.com", "Deliver exceptional user experiences. Services: User Onboarding, Product Tours, Feature Adoption, NPS Surveys, Analytics."],
    "Mixpanel": ["Mixpanel", "https://mixpanel.com", "Powerful, self-serve product analytics. Services: Product Analytics, Event Tracking, User Segmentation, A/B Testing, Reporting."],
    "Heap": ["Heap", "https://heap.io", "Data to every decision. Services: Product Analytics, Event Tracking, User Segmentation, A/B Testing, Reporting."],
    "Optimizely": ["Optimizely", "https://optimizely.com", "Experiment everywhere. Services: A/B Testing, Personalization, Recommendations, Feature Management, Web Experimentation."],
    "Unbounce": ["Unbounce", "https://unbounce.com", "Build, Publish & A/B Test Landing Pages Without I.T. Services: Landing Page Builder, A/B Testing, Popups, Sticky Bars, Integrations."],
    "Instapage": ["Instapage", "https://instapage.com", "Build Personalized Post-Click Experiences at Scale. Services: Landing Page Builder, A/B Testing, Personalization, Ad Mapping, Analytics."],
    "Leadpages": ["Leadpages", "https://leadpages.com", "Generate leads and increase revenue. Services: Landing Page Builder, Website Builder, Popups, Alert Bars, Integrations."],
    "Landingi": ["Landingi", "https://landingi.com", "Create, publish & optimize landing pages. Services: Landing Page Builder, Popups, A/B Testing, Integrations, Analytics."],
    "Google Optimize": ["Google Optimize", "https://optimize.google.com", "A/B testing and personalization. Services: A/B Testing, Multivariate Testing, Personalization, Analytics Integration, Experimentation."],
    "VWO": ["VWO", "https://vwo.com", "All-in-one platform to optimize your digital experiences. Services: A/B Testing, Multivariate Testing, Personalization, Heatmaps, Funnels."],
    "Crazy Egg": ["Crazy Egg", "https://crazyegg.com", "Website optimization made easy. Services: Heatmaps, Scrollmaps, Session Recordings, A/B Testing, User Feedback."],
    "Hotjar": ["Hotjar", "https://hotjar.com", "See how visitors are really using your website. Services: Heatmaps, Session Recordings, Surveys, Feedback, Analytics."],
    "FullStory": ["FullStory", "https://fullstory.com", "A better way to build, measure, and optimize digital experiences. Services: Session Replay, Heatmaps, User Journeys, Conversions, Integrations."],
    "Smartlook": ["Smartlook", "https://smartlook.com", "Qualitative analytics for websites and mobile apps. Services: Session Recordings, Heatmaps, Funnel Analysis, User Analytics, Integrations."],
    "SessionCam": ["SessionCam", "https://sessioncam.com", "Customer experience analytics for your website. Services: Session Replay, Heatmaps, Funnel Analysis, Error Detection, Integrations."],
    "ContentSquare": ["ContentSquare", "https://contentsquare.com", "The leading experience analytics platform. Services: Session Replay, Heatmaps, User Journeys, Zone-Based Heatmaps, AI Insights."],
    "LogRocket": ["LogRocket", "https://logrocket.com", "Understand problems affecting your users. Services: Session Replay, Performance Monitoring, Error Tracking, Console Logs, User Insights."],
    "BugSnag": ["BugSnag", "https://bugsnag.com", "Powerful error monitoring & reporting. Services: Error Monitoring, Bug Reporting, User Impact Analysis, Diagnostics, Integrations."],
    "Sentry": ["Sentry", "https://sentry.io", "Application Monitoring and Error Tracking Software. Services: Error Monitoring, Performance Monitoring, Release Health, User Feedback, Integrations."],
    "Rollbar": ["Rollbar", "https://rollbar.com", "Automate error monitoring and triaging. Services: Error Monitoring, Bug Reporting, User Impact Analysis, Diagnostics, Integrations."],
    "Raygun": ["Raygun", "https://raygun.com", "Monitor every part of your software stack. Services: Error Monitoring, Performance Monitoring, Real User Monitoring, Crash Reporting, Diagnostics."],
    "Airbrake": ["Airbrake", "https://airbrake.io", "Error monitoring and performance insight for your entire app stack. Services: Error Monitoring, Performance Monitoring, User Impact Analysis, Diagnostics, Integrations."],
    "TrackJS": ["TrackJS", "https://trackjs.com", "JavaScript Error Monitoring. Services: Error Monitoring, Error Reporting, User Impact Analysis, Diagnostics, Integrations."],
    "Prometheus": ["Prometheus", "https://prometheus.io", "Monitoring system & time series database. Services: Metrics Collection, Alerting, Time Series Database, Data Visualization, Integrations."],
    "Grafana": ["Grafana", "https://grafana.com", "The open-source platform for monitoring and observability. Services: Data Visualization, Dashboards, Alerting, Integrations, Graphing."],
    "Kibana": ["Kibana", "https://www.elastic.co/kibana", "Explore, visualize, and analyze your data. Services: Data Visualization, Dashboards, Alerting, Monitoring, Reporting."],
    "Splunk": ["Splunk", "https://splunk.com", "Turn data into doing. Services: Data Analytics, Monitoring, Security, Log Management, Cloud Services."],
    "Datadog": ["Datadog", "https://datadog.com", "Monitor, troubleshoot, and secure your applications. Services: Infrastructure Monitoring, Application Performance Monitoring, Log Management, Security Monitoring, Cloud Monitoring."],
    "New Relic": ["New Relic", "https://newrelic.com", "Observability made simple. Services: Application Monitoring, Infrastructure Monitoring, Log Management, Real User Monitoring, AI Monitoring."],
    "AppDynamics": ["AppDynamics", "https://appdynamics.com", "Observability, AI, and Machine Learning for your entire stack. Services: Application Performance Monitoring, Business Performance Monitoring, Real User Monitoring, Log Management, Cloud Monitoring."],
    "Dynatrace": ["Dynatrace", "https://dynatrace.com", "The leader in cloud observability. Services: Application Performance Monitoring, Infrastructure Monitoring, AIOps, Real User Monitoring, Security Monitoring."],
    "Honeycomb": ["Honeycomb", "https://honeycomb.io", "Observability for your software. Services: Event-Based Monitoring, Distributed Tracing, Metrics, Logging, Alerting."],
    "PagerDuty": ["PagerDuty", "https://pagerduty.com", "Incident response, on-call, and notification management. Services: Incident Management, On-Call Scheduling, Automation, Analytics, Integrations."],
    "Opsgenie": ["Opsgenie", "https://opsgenie.com", "Modern incident management. Services: Incident Response, On-Call Scheduling, Alerting, Automation, Reporting."],
    "VictorOps": ["VictorOps", "https://victorops.com", "Incident Management for High-Velocity Teams. Services: Incident Response, On-Call Scheduling, Alerting, Reporting, Automation."],
    "Statuspage": ["Statuspage", "https://statuspage.io", "Communicate status to your users. Services: Status Pages, Incident Communication, Monitoring, Reporting, Integrations."],
    "Status.io": ["Status.io", "https://status.io", "Status Pages for Your Infrastructure. Services: Status Pages, Incident Communication, Monitoring, Reporting, Integrations."],
    "Better Uptime": ["Better Uptime", "https://betteruptime.com", "Uptime monitoring and incident management. Services: Uptime Monitoring, Incident Management, On-Call Scheduling, Reporting, Integrations."],
    "Pingdom": ["Pingdom", "https://pingdom.com", "Website Performance Monitoring. Services: Uptime Monitoring, Real User Monitoring, Transaction Monitoring, Alerts, Reporting."],
    "UptimeRobot": ["UptimeRobot", "https://uptimerobot.com", "Website Monitoring Service. Services: Uptime Monitoring, Downtime Alerts, Reporting, Integrations, Performance Monitoring."],
    "Site24x7": ["Site24x7", "https://site24x7.com", "All-in-One Monitoring Solution. Services: Website Monitoring, Server Monitoring, Network Monitoring, Cloud Monitoring, Application Performance Monitoring."],
    "Monitis": ["Monitis", "https://monitis.com", "All-in-One Monitoring Solution. Services: Website Monitoring, Server Monitoring, Network Monitoring, Cloud Monitoring, Application Performance Monitoring."],
    "Nagios": ["Nagios", "https://nagios.org", "The Industry Standard in IT Infrastructure Monitoring. Services: Network Monitoring, Server Monitoring, Application Monitoring, Log Management, Reporting."],
    "Zabbix": ["Zabbix", "https://zabbix.com", "Enterprise-Class Monitoring Solution. Services: Network Monitoring, Server Monitoring, Application Monitoring, Cloud Monitoring, Reporting."],
    "PRTG Network Monitor": ["PRTG Network Monitor", "https://paessler.com", "Unified Monitoring Solution. Services: Network Monitoring, Server Monitoring, Application Monitoring, Cloud Monitoring, Reporting."],
    "SolarWinds Network Performance Monitor": ["SolarWinds Network Performance Monitor", "https://solarwinds.com", "Comprehensive Network Monitoring. Services: Network Monitoring, Server Monitoring, Application Monitoring, Cloud Monitoring, Reporting."],
    "ThousandEyes": ["ThousandEyes", "https://thousandeyes.com", "Internet and Cloud Intelligence. Services: Network Monitoring, Internet Monitoring, Application Monitoring, Cloud Monitoring, Reporting."],
    "Grafana Cloud": ["Grafana Cloud", "https://grafana.com/products/cloud", "Observability platform with metrics, logs, and traces. Services: Monitoring, Logging, Tracing, Dashboards, Alerting."],
    "Elastic Cloud": ["Elastic Cloud", "https://elastic.co/cloud", "Hosted Elasticsearch, Kibana, and more. Services: Search, Logging, Security, Observability, Cloud Deployment."],
    "Sumo Logic": ["Sumo Logic", "https://sumologic.com", "Continuous Intelligence. Services: Log Management, Security Analytics, Cloud Monitoring, Application Monitoring, Reporting."],
    "Graylog": ["Graylog", "https://graylog.org", "Log Management and SIEM. Services: Log Management, Security Analytics, Cloud Monitoring, Application Monitoring, Reporting."],
    "LogDNA": ["LogDNA", "https://logdna.com", "Centralized Log Management. Services: Log Management, Security Analytics, Cloud Monitoring, Application Monitoring, Reporting."],
    "Papertrail": ["Papertrail", "https://papertrailapp.com", "Log Management for Your Applications. Services: Log Management, Real-Time Tail, Alerts, Reporting, Integrations."],
    "Scalyr": ["Scalyr", "https://scalyr.com", "Fast and Efficient Log Management. Services: Log Management, Real-Time Tail, Alerts, Reporting, Integrations."],
    "Loggly": ["Loggly", "https://loggly.com", "Cloud-Based Log Management. Services: Log Management, Real-Time Tail, Alerts, Reporting, Integrations."],
    "Kibana": ["Kibana", "https://elastic.co/kibana", "Explore, visualize, and analyze your data. Services: Data Visualization, Dashboards, Alerting, Monitoring, Reporting."],
    "Tableau": ["Tableau", "https://tableau.com", "Visual Analytics Platform. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Looker": ["Looker", "https://looker.com", "Modern Data Platform. Services: Business Intelligence, Data Analytics, Data Exploration, Reporting, Dashboards."],
    "Power BI": ["Power BI", "https://powerbi.microsoft.com", "Business analytics service by Microsoft. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Qlik Sense": ["Qlik Sense", "https://qlik.com", "Data Analytics and Visualization. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Domo": ["Domo", "https://domo.com", "Business Cloud. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Sisense": ["Sisense", "https://sisense.com", "Simplifying Business Intelligence for Complex Data. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Mode": ["Mode", "https://mode.com", "Collaborative data science and analytics platform. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Redash": ["Redash", "https://redash.io", "Connect to any data source, easily visualize, dashboard and share your data. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Chartio": ["Chartio", "https://chartio.com", "Create powerful dashboards. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Metabase": ["Metabase", "https://metabase.com", "Open Source Data Analytics. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Google Data Studio": ["Google Data Studio", "https://datastudio.google.com", "Free data visualization and reporting. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Zoho Analytics": ["Zoho Analytics", "https://zoho.com/analytics", "Data Analytics for any business. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "SAP Analytics Cloud": ["SAP Analytics Cloud", "https://sapanalytics.cloud", "Everything you need, all in one place. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "MicroStrategy": ["MicroStrategy", "https://microstrategy.com", "Analytics and Mobility. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Alteryx": ["Alteryx", "https://alteryx.com", "Discover the world of data science and analytics. Services: Data Preparation, Data Blending, Analytics, Reporting, Machine Learning."],
    "TIBCO Spotfire": ["TIBCO Spotfire", "https://spotfire.tibco.com", "Data Analytics and Visualization. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Yellowfin": ["Yellowfin", "https://yellowfinbi.com", "Analytics and Business Intelligence. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "GoodData": ["GoodData", "https://gooddata.com", "Analytics Platform for Embedded Analytics. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Periscope Data": ["Periscope Data", "https://periscopedata.com", "Data Analysis and Visualization. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Grow": ["Grow", "https://grow.com", "Data Visualization and Business Dashboards. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "Cumul.io": ["Cumul.io", "https://cumul.io", "Create powerful dashboards. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "AnswerRocket": ["AnswerRocket", "https://answerrocket.com", "AI-Powered Analytics. Services: Data Visualization, Dashboards, Reporting, Data Integration, Analytics."],
    "KNIME": ["KNIME", "https://knime.com", "Open for Innovation. Services: Data Analytics, Data Mining, Machine Learning, Reporting, Data Integration."],
    "RapidMiner": ["RapidMiner", "https://rapidminer.com", "Data Science Platform. Services: Data Analytics, Data Mining, Machine Learning, Reporting, Data Integration."],
    "H2O.ai": ["H2O.ai", "https://h2o.ai", "AI and Machine Learning Platform. Services: Data Analytics, Machine Learning, Reporting, Data Integration, AI."],
    "DataRobot": ["DataRobot", "https://datarobot.com", "AI Cloud Platform. Services: Data Analytics, Machine Learning, Reporting, Data Integration, AI."],
    "Databricks": ["Databricks", "https://databricks.com", "Unified Data Analytics Platform. Services: Data Analytics, Machine Learning, Reporting, Data Integration, AI."],
    "Qubole": ["Qubole", "https://qubole.com", "Data Lake Platform. Services: Data Analytics, Data Management, Machine Learning, Reporting, Data Integration."],
    "Snowflake": ["Snowflake", "https://snowflake.com", "Cloud Data Platform. Services: Data Analytics, Data Management, Data Integration, Reporting, Machine Learning."],
    "Cloudera": ["Cloudera", "https://cloudera.com", "Enterprise Data Cloud. Services: Data Analytics, Data Management, Machine Learning, Reporting, Data Integration."],
    "MapR": ["MapR", "https://mapr.com", "Data Platform for AI and Analytics. Services: Data Analytics, Data Management, Machine Learning, Reporting, Data Integration."],
    "Hortonworks": ["Hortonworks", "https://hortonworks.com", "Data Platform. Services: Data Analytics, Data Management, Machine Learning, Reporting, Data Integration."],
    "Datorama": ["Datorama", "https://datorama.com", "Marketing Intelligence. Services: Data Analytics, Data Management, Reporting, Data Integration, AI."],
    "Segment": ["Segment", "https://segment.com", "Customer Data Platform. Services: Data Analytics, Data Management, Reporting, Data Integration, Customer Data."],
    "Fivetran": ["Fivetran", "https://fivetran.com", "Automated Data Integration. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Stitch": ["Stitch", "https://stitchdata.com", "Simple, extensible ETL built for data teams. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Talend": ["Talend", "https://talend.com", "Data Integration and Integrity. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Informatica": ["Informatica", "https://informatica.com", "Enterprise Cloud Data Management. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "SnapLogic": ["SnapLogic", "https://snaplogic.com", "Intelligent Integration Platform. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "MuleSoft": ["MuleSoft", "https://mulesoft.com", "Connect Any Application, Data, or Device. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Apache Nifi": ["Apache Nifi", "https://nifi.apache.org", "Data Integration and Processing. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Pentaho": ["Pentaho", "https://pentaho.com", "Data Integration and Analytics. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Matillion": ["Matillion", "https://matillion.com", "Data Transformation for Cloud Data Warehouses. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Xplenty": ["Xplenty", "https://xplenty.com", "Cloud-Based Data Integration Platform. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Alooma": ["Alooma", "https://alooma.com", "Real-Time Data Pipeline. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Google Dataflow": ["Google Dataflow", "https://cloud.google.com/dataflow", "Unified stream and batch data processing. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "AWS Glue": ["AWS Glue", "https://aws.amazon.com/glue", "Fully managed ETL service. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Azure Data Factory": ["Azure Data Factory", "https://azure.microsoft.com/services/data-factory", "Cloud-based data integration service. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Google Pub/Sub": ["Google Pub/Sub", "https://cloud.google.com/pubsub", "Messaging for event-driven systems. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "AWS Kinesis": ["AWS Kinesis", "https://aws.amazon.com/kinesis", "Real-time data streaming. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Apache Kafka": ["Apache Kafka", "https://kafka.apache.org", "Distributed event streaming platform. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Confluent": ["Confluent", "https://confluent.io", "Data in motion. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "StreamSets": ["StreamSets", "https://streamsets.com", "DataOps platform for modern data integration. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "HVR Software": ["HVR Software", "https://hvr-software.com", "Real-Time Data Replication. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Flink": ["Flink", "https://flink.apache.org", "Stream processing for real-time analytics. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Airbyte": ["Airbyte", "https://airbyte.io", "Open-source data integration. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Presto": ["Presto", "https://prestodb.io", "Distributed SQL query engine for big data. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Trino": ["Trino", "https://trino.io", "Fast SQL query engine for big data. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Dremio": ["Dremio", "https://dremio.com", "SQL Lakehouse Platform. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Starburst": ["Starburst", "https://starburst.io", "Analytics Anywhere. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Snowplow": ["Snowplow", "https://snowplow.io", "Behavioral Data Platform. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "RudderStack": ["RudderStack", "https://rudderstack.com", "Customer Data Platform for developers. Services: Data Analytics, Data Management, Reporting, Data Integration, ETL."],
    "Segment": ["Segment", "https://segment.com", "Customer Data Platform. Services: Data Analytics, Data Management, Reporting, Data Integration, Customer Data."]
};

let index = 0;

for (let key in data) {
    let queryLower = query.toLowerCase();
    let keyLower = key.toLowerCase();
    let data2Lower = data[key][2].toLowerCase();

    if (queryLower.includes(keyLower) || keyLower.includes(queryLower) || data2Lower.includes(queryLower)) {
        index++;
        console.log(data[key][0]);
        let li = document.createElement("li");
        let link = document.createElement("a");
        let br = document.createElement("br");
        link.innerHTML = data[key][0];
        link.href = data[key][1];
        li.appendChild(link);
        document.getElementById("ul").appendChild(li);
        document.getElementById("ul").appendChild(br);
    }
}
